//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANT_TEMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANT_TEMA()
        {
            this.ANT_PRODUTO_TEMATRANS = new HashSet<ANT_PRODUTO_TEMATRANS>();
            this.PRODUTO_BKP = new HashSet<PRODUTO_BKP>();
        }
    
        public decimal TEMA_ID { get; set; }
        public string TEMA_DESCRICAO { get; set; }
        public string TEMA_TIPO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANT_PRODUTO_TEMATRANS> ANT_PRODUTO_TEMATRANS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_BKP> PRODUTO_BKP { get; set; }
    }
}
