//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANT_DISCIPLINA_TIPO
    {
        public decimal DTIP_ID { get; set; }
        public Nullable<decimal> DTIP_DISC { get; set; }
        public Nullable<decimal> DTIP_TIPO { get; set; }
        public Nullable<decimal> DTIP_SEGM { get; set; }
        public Nullable<decimal> DTIP_AEDU { get; set; }
        public Nullable<decimal> DTIP_COMP { get; set; }
        public Nullable<decimal> DTIP_SEQU { get; set; }
    }
}
