//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANT_T_AUTORIA
    {
        public decimal AUTO_ID { get; set; }
        public string AUTO_NOMECON { get; set; }
        public string AUTO_NOMECAPA { get; set; }
        public Nullable<decimal> AUTO_PFUN { get; set; }
        public Nullable<System.DateTime> AUTO_DATALIBERA { get; set; }
        public Nullable<System.DateTime> AUTO_DATAVCTO { get; set; }
        public string AUTO_RENOVAUTO { get; set; }
        public Nullable<int> AUTO_QTDEMESES { get; set; }
        public Nullable<decimal> AUTO_PCRECEBDA { get; set; }
        public string AUTO_REPASSE { get; set; }
        public Nullable<System.DateTime> AUTO_DATALIMITE { get; set; }
        public Nullable<decimal> AUTO_PROD { get; set; }
        public string AUTO_NACIONALIDADE { get; set; }
        public string AUTO_NATURALIDADE { get; set; }
        public Nullable<int> AUTO_REPARTEIMP { get; set; }
        public Nullable<int> AUTO_REPARTEREIMP { get; set; }
    }
}
