//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANT_TIPO_ESPECIFICACAO
    {
        public decimal TESP_ID { get; set; }
        public string TESP_DESCRICAO { get; set; }
        public Nullable<decimal> TESP_ETEC { get; set; }
    
        public virtual ANT_ESPECIFICACAO_TECNICA ANT_ESPECIFICACAO_TECNICA { get; set; }
    }
}
