//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANT_COLECAO
    {
        public decimal COLE_ID { get; set; }
        public string COLE_DESCRICAO { get; set; }
        public Nullable<decimal> COLE_TIPO { get; set; }
        public Nullable<decimal> COLE_SEGM { get; set; }
    }
}
