//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANT_PRODUTO_FUNCAO
    {
        public decimal PFUN_ID { get; set; }
        public Nullable<decimal> PFUN_FCAO { get; set; }
        public Nullable<decimal> PFUN_AUTO { get; set; }
    
        public virtual ANT_AUTORIA ANT_AUTORIA { get; set; }
        public virtual ANT_FUNCAO ANT_FUNCAO { get; set; }
    }
}
