//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANT_PRODUTO_TEMATRANS
    {
        public decimal PTEM_ID { get; set; }
        public Nullable<decimal> PTEM_TEMA { get; set; }
        public Nullable<decimal> PTEM_PROD { get; set; }
    
        public virtual PRODUTO_BKP PRODUTO_BKP { get; set; }
        public virtual ANT_TEMA ANT_TEMA { get; set; }
    }
}
