//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANT_ESPECIFICACAO_TECNICA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANT_ESPECIFICACAO_TECNICA()
        {
            this.ANT_PRODUTO_ESPTECNICA = new HashSet<ANT_PRODUTO_ESPTECNICA>();
            this.ANT_TIPO_ESPECIFICACAO = new HashSet<ANT_TIPO_ESPECIFICACAO>();
        }
    
        public decimal ETEC_ID { get; set; }
        public string ETEC_DESCRICAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANT_PRODUTO_ESPTECNICA> ANT_PRODUTO_ESPTECNICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANT_TIPO_ESPECIFICACAO> ANT_TIPO_ESPECIFICACAO { get; set; }
    }
}
