//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANT_ANO_EDUCACAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANT_ANO_EDUCACAO()
        {
            this.ANT_FAIXA_ETARIA = new HashSet<ANT_FAIXA_ETARIA>();
            this.PRODUTO_BKP = new HashSet<PRODUTO_BKP>();
        }
    
        public decimal AEDU_ID { get; set; }
        public string AEDU_DESCRICAO { get; set; }
        public Nullable<decimal> AEDU_SEGM { get; set; }
    
        public virtual SEGMENTO SEGMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANT_FAIXA_ETARIA> ANT_FAIXA_ETARIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUTO_BKP> PRODUTO_BKP { get; set; }
    }
}
