//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANT_FAIXA_ETARIA
    {
        public decimal FETA_ID { get; set; }
        public string FETA_DESCRICAO { get; set; }
        public Nullable<decimal> FETA_AEDU { get; set; }
    
        public virtual ANT_ANO_EDUCACAO ANT_ANO_EDUCACAO { get; set; }
    }
}
