//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANT_T_HISTORICO_INTEGRACAO_PROTHEUS
    {
        public int ID_REGISTRO { get; set; }
        public Nullable<int> ID_PRODUTO { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string MENSAGEM { get; set; }
        public System.DateTime DATA { get; set; }
        public int ID_USUARIO { get; set; }
    }
}
