//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANT_A_TIPO_SISTEMA
    {
        public int ID_TIPO_SISTEMA { get; set; }
        public string DESCRICAO { get; set; }
        public string DOMINIO { get; set; }
        public bool ATIVO { get; set; }
    }
}
