//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTOSAUTORIA
    {
        public int DOC_ID { get; set; }
        public int AUTO_ID { get; set; }
        public string CAMINHOARQUIVO { get; set; }
        public string NOME { get; set; }
        public string CAMINHOLOCAL { get; set; }
    }
}
