//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENVIO_APROVACAO
    {
        public Nullable<decimal> ENV_CONTADOR { get; set; }
        public string DIG { get; set; }
        public Nullable<System.DateTime> INCLUSAO_DT { get; set; }
        public string NOME_ARQUIVO { get; set; }
        public string STATUS_EDITOR { get; set; }
        public string EDITOR { get; set; }
        public Nullable<System.DateTime> EDITOR_DT { get; set; }
        public string AUTOR { get; set; }
        public Nullable<System.DateTime> AUTOR_DT { get; set; }
        public string STATUS_AUTOR { get; set; }
        public Nullable<decimal> SEQUENCIA { get; set; }
        public byte[] IMAGEM { get; set; }
        public string LEGENDA_AUTOR { get; set; }
        public string OBS { get; set; }
        public decimal ENVIO_APROVACAO_CONTADOR { get; set; }
        public string LEGENDA_OLD { get; set; }
        public string OBS_AUTOR { get; set; }
        public string OBS_EDITOR { get; set; }
        public string ILUSTRADOR { get; set; }
        public string ILUSTRADOR_USUARIO_LIBERACAO { get; set; }
        public Nullable<System.DateTime> ILUSTRADOR_DATA_LIBERACAO { get; set; }
        public string ILUSTRADOR_USUARIO_REPROVA { get; set; }
        public Nullable<System.DateTime> ILUSTRADOR_DATA_REPROVA { get; set; }
        public string ILUSTRADOR_MOTV_REPROVA { get; set; }
        public string ILUSTRADOR_IMG_OBS { get; set; }
        public string ILUSTRADOR_IMG_OBS_LIBERA { get; set; }
        public string LINK { get; set; }
        public string ICONO_MOTV_REPROVA { get; set; }
        public Nullable<System.DateTime> ICONO_DATA_REPROVA { get; set; }
        public string ICONO_USUARIO_REPROVA { get; set; }
        public string IMAGEM_ALTURA { get; set; }
        public string IMAGEM_LARGURA { get; set; }
        public string LEGENDA { get; set; }
        public string ID_ELVIS { get; set; }
    }
}
