//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENVIO_OBRA_ELVIS
    {
        public string OBRA { get; set; }
        public string STATUS { get; set; }
        public string TIPO { get; set; }
        public Nullable<System.DateTime> EMISSAO { get; set; }
        public string DIG { get; set; }
        public string NOME_ARQUIVO { get; set; }
        public string FORNECEDOR { get; set; }
        public string LOJA { get; set; }
        public Nullable<double> CODIGO { get; set; }
        public string DIGA { get; set; }
        public string SITUACAO { get; set; }
        public string OPERADOR { get; set; }
        public string TAMANHO { get; set; }
        public decimal ENV_CONTADOR { get; set; }
        public Nullable<double> VALOR { get; set; }
        public string AUTORIZACAO { get; set; }
        public string TEXTO { get; set; }
        public byte[] IMAGEM { get; set; }
        public string TEXTO_A { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> MOVIMENTADO { get; set; }
        public string ORIGEM { get; set; }
        public string LEG_FIM { get; set; }
        public string REFERENCIA { get; set; }
        public Nullable<System.DateTime> VENCIMENTO { get; set; }
        public string REQUER_AUTOR { get; set; }
        public string OBRA_ANTIGA { get; set; }
        public string LEGENDA_OLD { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<System.DateTime> DATA_ALTERACAO_DIGA { get; set; }
        public string OBS { get; set; }
        public string LEGENDA_AUTOR_OLD { get; set; }
        public string LICENC { get; set; }
        public string CREDITO { get; set; }
        public string REQ_GERADA { get; set; }
        public Nullable<System.DateTime> REQ_DATA { get; set; }
        public string REQ_INCLUIDOR { get; set; }
        public Nullable<decimal> REQUISICAO { get; set; }
        public Nullable<System.DateTime> DATA_FINALIZADA { get; set; }
        public string QUEM_FINALIZOU { get; set; }
        public string NF { get; set; }
        public string COD_INTERNO { get; set; }
        public string USERALT { get; set; }
        public string DISCIPLINA { get; set; }
        public string ANO { get; set; }
        public string ENTRA_GALERIA_IMAGEM { get; set; }
        public string PORTAL { get; set; }
        public string UNIDADE { get; set; }
        public string PAGINA { get; set; }
        public string LEGENDA { get; set; }
        public string OBS_ICONOGRAFIA { get; set; }
        public string CONTRATO_GERADO { get; set; }
        public string CONTRATO_USUARIO { get; set; }
        public Nullable<System.DateTime> CONTRATO_INCLUIDO { get; set; }
        public Nullable<double> CONTRATO { get; set; }
        public string LEGENDA_AUTOR_OLD2 { get; set; }
        public string LEGENDA_AUTOR { get; set; }
        public string INFO_DIAGRAMACAO { get; set; }
        public string ID_ELVIS { get; set; }
        public string NREQUISICAO { get; set; }
    }
}
