//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class FASE_SERVICO
    {
        public string TIPO_SERVICO { get; set; }
        public string SERVICO_DESCRICAO { get; set; }
        public string FASE { get; set; }
        public string SERVICO_OBS { get; set; }
        public string SERV_UNI { get; set; }
        public string CCUSTO { get; set; }
        public decimal CONTADOR { get; set; }
        public string DIG { get; set; }
        public Nullable<System.DateTime> INCLUSAO { get; set; }
        public string DIG_ALT { get; set; }
        public Nullable<System.DateTime> ALTERACAO { get; set; }
        public string REQUISICAO { get; set; }
        public string REQUISICAO_ORDEM { get; set; }
        public string GRUPO_CONT_JURIDICA { get; set; }
        public string GRUPO_CONT_FISICA { get; set; }
        public string EXCLUIDO { get; set; }
        public string CCUSTOS_APROPRIACAO { get; set; }
        public string CCUSTOS_REQUISICAO { get; set; }
        public string NATUREZA_PJ { get; set; }
        public string NATUREZA_PF { get; set; }
    }
}
