//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flipbook_Consultor_bkp
    {
        public System.Guid Id { get; set; }
        public string ISBN { get; set; }
        public string Nome { get; set; }
        public string FlipbookURL { get; set; }
        public string CapaURL { get; set; }
        public bool EBSA { get; set; }
        public string Parceiro { get; set; }
        public string Autor { get; set; }
        public decimal Materia { get; set; }
        public decimal Ano { get; set; }
        public decimal Segmento { get; set; }
        public string Colecao { get; set; }
        public decimal Ano_Publicacao { get; set; }
    }
}
