//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPO
    {
        public int ID_GRUPO { get; set; }
        public string DESCRICAO { get; set; }
        public bool ATIVO { get; set; }
        public Nullable<System.DateTime> DATA_CRIACAO { get; set; }
        public Nullable<System.DateTime> DATA_ALTERACAO { get; set; }
        public string USUARIO { get; set; }
        public string DEPARTAMENTO { get; set; }
        public System.Guid ID_GRUPO_AD { get; set; }
    
        public virtual GRUPO GRUPO1 { get; set; }
        public virtual GRUPO GRUPO2 { get; set; }
    }
}
