//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTEGRACAO_ADMPORTAL_CONSULTOR
    {
        public System.Guid GUID { get; set; }
        public decimal COD_DIVULGADOR { get; set; }
        public System.DateTime DATA { get; set; }
        public bool ATIVO { get; set; }
    }
}
