//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIVRO
    {
        public int CONTADOR { get; set; }
        public string CODIGO { get; set; }
        public string OBRA { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string SERIE { get; set; }
        public string ENCADERNACAO { get; set; }
        public string FORMATO { get; set; }
        public Nullable<int> CORES { get; set; }
        public Nullable<int> PAGINAS { get; set; }
        public string TIPO { get; set; }
        public string STATUS { get; set; }
        public string DSTATUS { get; set; }
        public string GRAVAR { get; set; }
        public Nullable<System.DateTime> INICIO { get; set; }
        public Nullable<System.DateTime> PREVISAO { get; set; }
        public Nullable<System.DateTime> TERMINO { get; set; }
        public string OBS { get; set; }
        public string PROJETO { get; set; }
        public string VOLUME { get; set; }
        public string OPERADOR { get; set; }
        public string DESCRICAO { get; set; }
        public string COLECAO { get; set; }
        public string CONDICAO { get; set; }
        public Nullable<int> SITUACAO { get; set; }
        public string COD_IMAGEM { get; set; }
        public string MATERIA { get; set; }
        public string AREA { get; set; }
        public Nullable<int> PAG_MP { get; set; }
        public Nullable<System.DateTime> DT_INC { get; set; }
        public string OPERADOR_ALT { get; set; }
        public Nullable<System.DateTime> DT_ALT { get; set; }
        public Nullable<System.DateTime> DATAD { get; set; }
        public Nullable<System.DateTime> DATAE { get; set; }
        public string INFGERAL { get; set; }
        public string DVD { get; set; }
        public string OBRA_ANTIGA { get; set; }
        public string PSEUDONIMO { get; set; }
        public string NM_EDITORA { get; set; }
        public string TITULO { get; set; }
        public string TITULO_ORIGINAL { get; set; }
        public Nullable<int> ANO_PUB { get; set; }
        public string COLABORADOR { get; set; }
        public string TEXT_COLAB { get; set; }
        public Nullable<int> EDICAO { get; set; }
        public string REIMP { get; set; }
        public string CO_EDICAO { get; set; }
        public string TIT_SC { get; set; }
        public Nullable<int> NUM_PUB { get; set; }
        public string P_PRECEDE { get; set; }
        public string INC_BIB { get; set; }
        public string INC_APEN { get; set; }
        public string TIT_ANT { get; set; }
        public string TIT_CON { get; set; }
        public string TIT_SUP { get; set; }
        public string TIT_OUT { get; set; }
        public string SUPLEM { get; set; }
        public string ISBN { get; set; }
        public string P_CHAVE { get; set; }
        public string CENTRO_CUSTO { get; set; }
        public string USER_TROCA_CODIGO { get; set; }
        public Nullable<System.DateTime> DATA_TROCA_CODIGO { get; set; }
        public string PRE_TRIAGEM { get; set; }
        public string TRIAGEM { get; set; }
        public string PROVAS { get; set; }
        public string NOVA_REFORMULADA { get; set; }
        public string REFORMULADA { get; set; }
        public string ANO_PROD { get; set; }
        public Nullable<System.DateTime> INICIO2 { get; set; }
        public Nullable<System.DateTime> PREVISAO2 { get; set; }
        public Nullable<System.DateTime> TERMINO2 { get; set; }
    }
}
