//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Flipbook_Consultor
    {
        public string ISBN { get; set; }
        public string Usuario_Email { get; set; }
        public System.DateTime Data_Inclusao { get; set; }
    }
}
