//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENU()
        {
            this.MENU1 = new HashSet<MENU>();
            this.MENU_GRUPO = new HashSet<MENU_GRUPO>();
            this.TB_REGRA_ACESSO_MENU_CADASTRO_PRODUTO = new HashSet<TB_REGRA_ACESSO_MENU_CADASTRO_PRODUTO>();
            this.TB_ABA_CADASTRO_PRODUTO = new HashSet<TB_ABA_CADASTRO_PRODUTO>();
        }
    
        public int ID_MENU { get; set; }
        public Nullable<int> ID_MENU_PAI { get; set; }
        public string DESCRICAO { get; set; }
        public string LINK { get; set; }
        public string ROTA { get; set; }
        public bool ATIVO { get; set; }
        public string NOME_CONTROLLER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU> MENU1 { get; set; }
        public virtual MENU MENU2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENU_GRUPO> MENU_GRUPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_REGRA_ACESSO_MENU_CADASTRO_PRODUTO> TB_REGRA_ACESSO_MENU_CADASTRO_PRODUTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ABA_CADASTRO_PRODUTO> TB_ABA_CADASTRO_PRODUTO { get; set; }
    }
}
