//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIDIA
    {
        public int MIDI_ID { get; set; }
        public string MIDI_DESCRICAO { get; set; }
        public string MIDI_UNIDVENDA { get; set; }
        public Nullable<int> MIDI_PLAT { get; set; }
    }
}
