//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class PESSOA
    {
        public decimal PESS_ID { get; set; }
        public string PESS_NOME { get; set; }
        public string PESS_CPF { get; set; }
        public string PESS_END { get; set; }
    }
}
