//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO_ESPTECNICA
    {
        public decimal PESP_ID { get; set; }
        public Nullable<decimal> PESP_ETEC { get; set; }
        public Nullable<decimal> PESP_PROD { get; set; }
    }
}
