//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO_BKP08012020
    {
        public decimal PROD_ID { get; set; }
        public Nullable<decimal> PROD_CDIS { get; set; }
        public Nullable<decimal> PROD_TEMA { get; set; }
        public Nullable<decimal> PROD_DISC { get; set; }
        public Nullable<int> PROD_MERCADO { get; set; }
        public string PROD_PROGRAMA { get; set; }
        public Nullable<decimal> PROD_TIPO { get; set; }
        public string PROD_SELO { get; set; }
        public Nullable<decimal> PROD_SEGM { get; set; }
        public Nullable<decimal> PROD_AEDU { get; set; }
        public Nullable<decimal> PROD_COMP { get; set; }
        public Nullable<int> PROD_FAIXAETARIA { get; set; }
        public Nullable<decimal> PROD_ASSU { get; set; }
        public Nullable<decimal> PROD_GTEX { get; set; }
        public string PROD_PREMIACAO { get; set; }
        public string PROD_VERSAO { get; set; }
        public string PROD_COLE { get; set; }
        public string PROD_TITULO { get; set; }
        public Nullable<decimal> PROD_EDICAO { get; set; }
        public Nullable<int> PROD_MIDI { get; set; }
        public Nullable<decimal> PROD_PAGINAS { get; set; }
        public string PROD_PLAT { get; set; }
        public Nullable<decimal> PROD_FORALTURA { get; set; }
        public Nullable<decimal> PROD_FORLARGURA { get; set; }
        public Nullable<decimal> PROD_PESO { get; set; }
        public Nullable<System.DateTime> PROD_PUBLICACAO { get; set; }
        public string PROD_ISBN { get; set; }
        public string PROD_STATUS { get; set; }
        public string PROD_CODBARRAS { get; set; }
        public string PROD_SINOPSE { get; set; }
        public Nullable<decimal> PROD_PRECO { get; set; }
        public string PROD_EBSA { get; set; }
        public string PROD_UNIDADE { get; set; }
        public string PROD_CODPROT { get; set; }
        public Nullable<bool> PROD_PUBLICADO { get; set; }
        public Nullable<System.DateTime> PROD_DATAPUBLICACAO { get; set; }
        public Nullable<int> PROD_ORIGEM { get; set; }
        public Nullable<bool> EXCLUIDO { get; set; }
        public Nullable<int> PROD_TIPO_PRODUTO { get; set; }
        public Nullable<int> PROD_UNIDADE_MEDIDA { get; set; }
        public Nullable<int> ID_GRUPO { get; set; }
        public Nullable<int> ID_SEGMENTO { get; set; }
        public string PROD_VIDEO { get; set; }
        public string PROD_NOME_CAPA { get; set; }
        public Nullable<int> ID_SELO { get; set; }
        public Nullable<int> ANO_PROGRAMA { get; set; }
    }
}
