//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto_Status
    {
        public int Id_Produto_Status { get; set; }
        public string Cod_Produto_Status { get; set; }
        public string Descricao_Produto_Status { get; set; }
    }
}
