//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO_BKP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUTO_BKP()
        {
            this.ANT_AUTORIA = new HashSet<ANT_AUTORIA>();
            this.ANT_PRODUTO_DATAESPECIAL = new HashSet<ANT_PRODUTO_DATAESPECIAL>();
            this.ANT_PRODUTO_ESPTECNICA = new HashSet<ANT_PRODUTO_ESPTECNICA>();
            this.ANT_PRODUTO_TEMATRANS = new HashSet<ANT_PRODUTO_TEMATRANS>();
            this.FICHATECNICA_BKP = new HashSet<FICHATECNICA_BKP>();
        }
    
        public decimal PROD_ID { get; set; }
        public Nullable<decimal> PROD_CDIS { get; set; }
        public Nullable<decimal> PROD_TEMA { get; set; }
        public Nullable<decimal> PROD_DISC { get; set; }
        public Nullable<int> PROD_MERCADO { get; set; }
        public string PROD_PROGRAMA { get; set; }
        public Nullable<decimal> PROD_TIPO { get; set; }
        public string PROD_SELO { get; set; }
        public Nullable<decimal> PROD_SEGM { get; set; }
        public Nullable<decimal> PROD_AEDU { get; set; }
        public Nullable<decimal> PROD_COMP { get; set; }
        public Nullable<int> PROD_FAIXAETARIA { get; set; }
        public Nullable<decimal> PROD_ASSU { get; set; }
        public Nullable<decimal> PROD_GTEX { get; set; }
        public string PROD_PREMIACAO { get; set; }
        public string PROD_VERSAO { get; set; }
        public string PROD_COLE { get; set; }
        public string PROD_TITULO { get; set; }
        public Nullable<decimal> PROD_EDICAO { get; set; }
        public Nullable<int> PROD_MIDI { get; set; }
        public Nullable<decimal> PROD_PAGINAS { get; set; }
        public string PROD_PLAT { get; set; }
        public Nullable<decimal> PROD_FORALTURA { get; set; }
        public Nullable<decimal> PROD_FORLARGURA { get; set; }
        public Nullable<decimal> PROD_PESO { get; set; }
        public Nullable<System.DateTime> PROD_PUBLICACAO { get; set; }
        public string PROD_ISBN { get; set; }
        public string PROD_STATUS { get; set; }
        public string PROD_CODBARRAS { get; set; }
        public string PROD_SINOPSE { get; set; }
        public Nullable<decimal> PROD_PRECO { get; set; }
        public string PROD_EBSA { get; set; }
        public string PROD_UNIDADE { get; set; }
        public string PROD_CODPROT { get; set; }
    
        public virtual ANT_ANO_EDUCACAO ANT_ANO_EDUCACAO { get; set; }
        public virtual ANT_ASSUNTO ANT_ASSUNTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANT_AUTORIA> ANT_AUTORIA { get; set; }
        public virtual ANT_COMPOSICAO ANT_COMPOSICAO { get; set; }
        public virtual ANT_CONTEUDO_DISCIPLINAR ANT_CONTEUDO_DISCIPLINAR { get; set; }
        public virtual ANT_DISCIPLINA ANT_DISCIPLINA { get; set; }
        public virtual ANT_GENERO_TEXTUAL ANT_GENERO_TEXTUAL { get; set; }
        public virtual ANT_MIDIA ANT_MIDIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANT_PRODUTO_DATAESPECIAL> ANT_PRODUTO_DATAESPECIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANT_PRODUTO_ESPTECNICA> ANT_PRODUTO_ESPTECNICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANT_PRODUTO_TEMATRANS> ANT_PRODUTO_TEMATRANS { get; set; }
        public virtual ANT_TEMA ANT_TEMA { get; set; }
        public virtual ANT_TIPO ANT_TIPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FICHATECNICA_BKP> FICHATECNICA_BKP { get; set; }
        public virtual SEGMENTO SEGMENTO { get; set; }
    }
}
