//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAMAIS_FAVORITOS
    {
        public int ID { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public string NOME_FAVORITADO { get; set; }
        public string RAMAL_FAVORITADO { get; set; }
        public string DEPARTAMENTO_FAVORITADO { get; set; }
    }
}
