//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUISICAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REQUISICAO()
        {
            this.REQUISICAO_OBRA = new HashSet<REQUISICAO_OBRA>();
            this.REQUISICAO_PARCELA = new HashSet<REQUISICAO_PARCELA>();
            this.REQUISICAO_SERVICO = new HashSet<REQUISICAO_SERVICO>();
        }
    
        public decimal ID { get; set; }
        public string DEPTO { get; set; }
        public Nullable<System.DateTime> EMISSAO { get; set; }
        public string FORNECEDOR { get; set; }
        public string LOJA { get; set; }
        public Nullable<double> VALOR { get; set; }
        public Nullable<System.DateTime> PRAZO_ENTREGA { get; set; }
        public Nullable<System.DateTime> PRAZO_PAGTO { get; set; }
        public string PESSOA { get; set; }
        public string FORMA_PAGTO { get; set; }
        public string CONFIRMAR_PAGTO { get; set; }
        public string DOC { get; set; }
        public string OBS { get; set; }
        public string APROVADO_SUPERVISOR { get; set; }
        public string APROVADO_GERENTE { get; set; }
        public string OUTROS_SERVICOS { get; set; }
        public string INCLUIDOR { get; set; }
        public Nullable<System.DateTime> INCLUIDO { get; set; }
        public string ALTERADOR { get; set; }
        public Nullable<System.DateTime> ALTERADO { get; set; }
        public string GERENTE { get; set; }
        public string SUPERVISOR { get; set; }
        public string OUTROS { get; set; }
        public string TELEFONE { get; set; }
        public string CONTATO { get; set; }
        public string DESC_PAG { get; set; }
        public Nullable<System.DateTime> DATA_APROV_SUPERVISOR { get; set; }
        public Nullable<System.DateTime> DATA_REPROV_SUPERVISOR { get; set; }
        public Nullable<System.DateTime> DATA_APROV_GERENTE { get; set; }
        public Nullable<System.DateTime> DATA_REPROV_GERENTE { get; set; }
        public string EXCLUIDO { get; set; }
        public Nullable<System.DateTime> DATA_EXCLUSAO { get; set; }
        public string EXCLUIDOR { get; set; }
        public string USER_ENVIO_FINANCEIRO { get; set; }
        public Nullable<System.DateTime> DATA_ENVIO_FINANCEIRO { get; set; }
        public Nullable<decimal> ID_REQUISICAO_DEPTO { get; set; }
        public Nullable<decimal> CONTADOR_CHAMADO { get; set; }
        public string USER_ENVIO_SOLIC_COMPROVANTE { get; set; }
        public Nullable<System.DateTime> DATA_ENVIO_SOLIC_COMPROVANTE { get; set; }
        public string OBSD { get; set; }
        public string MOEDA { get; set; }
        public string OPSIMP { get; set; }
        public string TIPODOC { get; set; }
        public string IMPOSTO_CALCULADO { get; set; }
        public Nullable<double> COFINS { get; set; }
        public Nullable<double> PIS { get; set; }
        public Nullable<double> CSL { get; set; }
        public Nullable<double> INSS { get; set; }
        public Nullable<double> ISS { get; set; }
        public Nullable<double> IRRF { get; set; }
        public Nullable<System.DateTime> IMPOSTO_CALCULADO_DATA { get; set; }
        public string FINANCEIRO_TRANSF { get; set; }
        public Nullable<System.DateTime> FINANCEIRO_TRANSF_DATA { get; set; }
        public Nullable<double> OE_INSS { get; set; }
        public Nullable<double> OE_BINSS { get; set; }
        public string FINANCEIRO_DIG { get; set; }
        public string CONTABIL_DIG { get; set; }
        public string EVCONF { get; set; }
        public Nullable<System.DateTime> DTEVCONF { get; set; }
        public string USEREVCONF { get; set; }
        public string CONTRATO { get; set; }
        public string ID_ELVIS { get; set; }
        public Nullable<bool> ELVIS_OK { get; set; }
        public string SERIE { get; set; }
        public string INTEGRADO_PROTHEUS { get; set; }
        public Nullable<bool> CANCELADA { get; set; }
        public Nullable<System.DateTime> DATA_CANCELAMENTO { get; set; }
        public string USER_CANCELAMENTO { get; set; }
        public Nullable<bool> ELVIS_ORIGEM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUISICAO_OBRA> REQUISICAO_OBRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUISICAO_PARCELA> REQUISICAO_PARCELA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUISICAO_SERVICO> REQUISICAO_SERVICO { get; set; }
    }
}
