//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUISICAO_PARCELA
    {
        public decimal ID { get; set; }
        public decimal ID_REQ { get; set; }
        public int NUMERO_PARCELA { get; set; }
        public double VALOR { get; set; }
        public System.DateTime DATA_PAGTO { get; set; }
    
        public virtual REQUISICAO REQUISICAO { get; set; }
    }
}
