//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUISICAO_SERVICO
    {
        public decimal ID { get; set; }
        public Nullable<decimal> ID_REQ { get; set; }
        public string SERVICO { get; set; }
        public string EXCLUIDO { get; set; }
        public Nullable<double> SERV_RATEIO { get; set; }
    
        public virtual REQUISICAO REQUISICAO { get; set; }
    }
}
