//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ABA_CADASTRO_PRODUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ABA_CADASTRO_PRODUTO()
        {
            this.TB_REGRA_ACESSO_ABA_CADASTRO_PRODUTO = new HashSet<TB_REGRA_ACESSO_ABA_CADASTRO_PRODUTO>();
        }
    
        public int ID_ABA { get; set; }
        public string DESCRICAO { get; set; }
        public int ID_MENU { get; set; }
        public string NOME_ABA { get; set; }
    
        public virtual MENU MENU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_REGRA_ACESSO_ABA_CADASTRO_PRODUTO> TB_REGRA_ACESSO_ABA_CADASTRO_PRODUTO { get; set; }
    }
}
