//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CONTEUDO_PP
    {
        public int ID_CONTEUDO { get; set; }
        public string NOME { get; set; }
        public string CAMINHO { get; set; }
        public string NOME_GUID { get; set; }
        public Nullable<int> USUARIO { get; set; }
        public Nullable<System.DateTime> DT_CADASTRO { get; set; }
        public Nullable<bool> ATIVO { get; set; }
        public string PRIMEIRA_PAGINA { get; set; }
    }
}
