//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CONTROLE_IMPRESSAO_PRODUTO
    {
        public long ID_CONTROLE_IMPRESSAO { get; set; }
        public long ID_PRODUTO { get; set; }
        public string CONT_IMP_EDICAO { get; set; }
        public string CONT_IMP_GRAFICA { get; set; }
        public string CONT_IMP_IMPRESSAO { get; set; }
        public Nullable<System.DateTime> CONT_IMP_DATA { get; set; }
        public Nullable<int> CONT_IMP_TIRAGEM { get; set; }
        public string CONT_IMP_OBS { get; set; }
    }
}
