//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_COLLECTION_ELVIS
    {
        public System.Guid ID_COLLECTION { get; set; }
        public string CODIGO_ELVIS { get; set; }
        public string NOME { get; set; }
        public string CAMINHO { get; set; }
        public string PARTE_LIVRO { get; set; }
        public string CODIGO_LIVRO { get; set; }
        public string CATEGORIA { get; set; }
        public string STATUS { get; set; }
        public System.DateTime DT_CADASTRO { get; set; }
        public Nullable<System.Guid> ID_LIVRO { get; set; }
    
        public virtual TB_LIVRO_ELVIS TB_LIVRO_ELVIS { get; set; }
    }
}
