//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CARGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CARGO()
        {
            this.TB_USUARIO_RM = new HashSet<TB_USUARIO_RM>();
        }
    
        public System.Guid ID_CARGO { get; set; }
        public string DESCRICAO { get; set; }
        public System.Guid ID_HIERARQUIA { get; set; }
        public Nullable<System.Guid> ID_GRUPO_PAINEL { get; set; }
        public System.DateTime DT_CADASTRO { get; set; }
        public Nullable<bool> ATIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_USUARIO_RM> TB_USUARIO_RM { get; set; }
    }
}
