//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CAMPO_ORIGEM
    {
        public System.Guid ID_CAMPO { get; set; }
        public string NOME_CAMPO { get; set; }
        public System.Guid ID_TABELA { get; set; }
        public string SCRIPT_CAMPO { get; set; }
        public bool ATIVO { get; set; }
        public string DESCRICAO { get; set; }
    }
}
