//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CADERNO_PRODUTO
    {
        public long ID_CADERNO { get; set; }
        public long ID_PRODUTO { get; set; }
        public Nullable<int> CADERNO_PAGINAS { get; set; }
        public Nullable<decimal> CADERNO_ALT { get; set; }
        public Nullable<decimal> CADERNO_LARG { get; set; }
        public Nullable<int> CADERNO_TIPO { get; set; }
        public string CADERNO_TIPO_OUTROS { get; set; }
        public string CADERNO_PESO { get; set; }
        public string CADERNO_MIOLO_CORES { get; set; }
        public string CADERNO_MIOLO_TP_PAPEL { get; set; }
        public string CADERNO_MIOLO_GRAMATURA { get; set; }
        public string CADERNO_MIOLO_OBS { get; set; }
        public string CADERNO_CAPA_CORES { get; set; }
        public string CADERNO_CAPA_TP_PAPEL { get; set; }
        public string CADERNO_CAPA_GRAMATURA { get; set; }
        public string CADERNO_CAPA_ORELHA { get; set; }
        public string CADERNO_CAPA_ACABAMENTO { get; set; }
        public string CADERNO_CAPA_OBS { get; set; }
        public string CADERNO_CAPA_ACAB_LOMBADA { get; set; }
    }
}
