//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CAPA_PRODUTO
    {
        public long ID_CAPA { get; set; }
        public long ID_PRODUTO { get; set; }
        public string CAPA_CORES { get; set; }
        public string CAPA_TIPO_PAPEL { get; set; }
        public string CAPA_GRAMATURA { get; set; }
        public string CAPA_ORELHA { get; set; }
        public string CAPA_ACABAMENTO { get; set; }
        public string CAPA_OBS { get; set; }
        public string CAPA_ACABAMENTO_LOMBADA { get; set; }
    }
}
