//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CONDICAO_COMERCIAL
    {
        public int ID_CONDICAO { get; set; }
        public string COD_EBSA { get; set; }
        public Nullable<decimal> PRECO { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public System.DateTime DT_LIBERACAO { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public int ID_HISTORICO { get; set; }
    }
}
