//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ENCARTE_PRODUTO
    {
        public long ID_ENCARTE { get; set; }
        public long ID_PRODUTO { get; set; }
        public string ENCARTE_TIPO { get; set; }
        public string ENCARTE_ACABAMENTO { get; set; }
        public string ENCARTE_PAPEL { get; set; }
        public string ENCARTE_GRAMATURA { get; set; }
        public string ENCARTE_FORMATO { get; set; }
        public string ENCARTE_COR { get; set; }
        public string ENCARTE_OUTROS { get; set; }
        public Nullable<int> ENCARTE_PAGINAS { get; set; }
    }
}
