//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_GERENTE_SUPERVISOR
    {
        public System.Guid ID_GERENTE_SUPERVISOR { get; set; }
        public System.Guid ID_GERENTE { get; set; }
        public System.Guid ID_SUPERVISOR { get; set; }
        public System.DateTime DT_CADASTRO { get; set; }
    
        public virtual TB_USUARIO_RM TB_USUARIO_RM { get; set; }
        public virtual TB_USUARIO_RM TB_USUARIO_RM1 { get; set; }
    }
}
