//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HISTORICO_IMPRESSAO
    {
        public int ID_HISTORICO { get; set; }
        public int PRODUTO_ID { get; set; }
        public Nullable<System.DateTime> DT_IMPRESSAO { get; set; }
        public Nullable<System.DateTime> DT_REGISTRO { get; set; }
        public Nullable<int> NUM_IMPRESSAO { get; set; }
        public string NOME_GRAFICA { get; set; }
        public Nullable<decimal> TIRAGEM { get; set; }
        public string OBS { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
    }
}
