//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_HIERARQUIA_PAINEL
    {
        public System.Guid ID_HIERARQUIA { get; set; }
        public string DESCRICAO { get; set; }
        public System.DateTime DT_CADASTRADO { get; set; }
        public int NIVEL { get; set; }
    }
}
