//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LINHA_PAINEL_META
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_LINHA_PAINEL_META()
        {
            this.TB_META_ANUAL = new HashSet<TB_META_ANUAL>();
            this.TB_META_FINANCEIRA = new HashSet<TB_META_FINANCEIRA>();
            this.TB_META_REAL = new HashSet<TB_META_REAL>();
        }
    
        public System.Guid ID_LINHA_META { get; set; }
        public System.Guid ID_META { get; set; }
        public string INDICADOR { get; set; }
        public string META { get; set; }
        public byte PESO { get; set; }
        public Nullable<System.Guid> ID_ORIGEM { get; set; }
    
        public virtual TB_CABECALHO_PAINEL_META TB_CABECALHO_PAINEL_META { get; set; }
        public virtual TB_ORIGEM_DADOS_PAINEL_META TB_ORIGEM_DADOS_PAINEL_META { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_META_ANUAL> TB_META_ANUAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_META_FINANCEIRA> TB_META_FINANCEIRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_META_REAL> TB_META_REAL { get; set; }
    }
}
