//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LIVRO_ELVIS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_LIVRO_ELVIS()
        {
            this.TB_COLLECTION_ELVIS = new HashSet<TB_COLLECTION_ELVIS>();
            this.TB_PARTE_LIVRO_ELVIS = new HashSet<TB_PARTE_LIVRO_ELVIS>();
        }
    
        public System.Guid ID_LIVRO { get; set; }
        public string CODIGO_LIVRO { get; set; }
        public System.DateTime DT_CADASTRO { get; set; }
        public string TITULO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_COLLECTION_ELVIS> TB_COLLECTION_ELVIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PARTE_LIVRO_ELVIS> TB_PARTE_LIVRO_ELVIS { get; set; }
    }
}
