//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MIOLO_PRODUTO
    {
        public long ID_MIOLO { get; set; }
        public long ID_PRODUTO { get; set; }
        public Nullable<int> MIOLO_PAGINAS { get; set; }
        public Nullable<decimal> MIOLO_FORM_ALT { get; set; }
        public Nullable<decimal> MIOLO_FORM_LARG { get; set; }
        public Nullable<decimal> MIOLO_FORM_PESO { get; set; }
        public string MIOLO_CORES { get; set; }
        public string MIOLO_TIPO_PAPEL { get; set; }
        public string MIOLO_GRAMATURA { get; set; }
        public string MIOLO_OBS { get; set; }
    }
}
