//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MIDIA_PRODUTO
    {
        public long ID_MIDIA { get; set; }
        public long ID_PRODUTO { get; set; }
        public Nullable<int> MIDIA_TIPO { get; set; }
        public string MIDIA_OUTROS { get; set; }
    }
}
