//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_META_REAL
    {
        public System.Guid ID_META_REAL { get; set; }
        public System.Guid ID_USUARIO_RM { get; set; }
        public Nullable<System.Guid> ID_LINHA_META { get; set; }
        public decimal REALIZADO { get; set; }
        public decimal PONDERADO { get; set; }
        public System.DateTime DATA_CRIACAO { get; set; }
    
        public virtual TB_LINHA_PAINEL_META TB_LINHA_PAINEL_META { get; set; }
        public virtual TB_USUARIO_RM TB_USUARIO_RM { get; set; }
    }
}
