//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PLATAFORMA_MIDIA
    {
        public int ID_PLATAFORMA_MIDIA { get; set; }
        public int ID_MIDIA { get; set; }
        public int ID_PLATAFORMA { get; set; }
    }
}
