//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PARTE_LIVRO_ELVIS
    {
        public System.Guid ID_PARTE_LIVRO_ELVIS { get; set; }
        public string DESCRICAO { get; set; }
        public System.DateTime DT_CADASTRO { get; set; }
        public System.Guid ID_LIVRO { get; set; }
    
        public virtual TB_LIVRO_ELVIS TB_LIVRO_ELVIS { get; set; }
    }
}
