//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PRODUTO_IMAGEM_CAPA
    {
        public System.Guid ID_PRODUTO_CAPA { get; set; }
        public string NOME_CAPA { get; set; }
        public string CAMINHO_ARQUIVO { get; set; }
        public decimal PROD_ID { get; set; }
        public string PROD_EBSA { get; set; }
        public System.DateTime DT_CADASTRO { get; set; }
    }
}
