//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RELATORIO_ELVIS
    {
        public System.Guid ID_LIVRO { get; set; }
        public string PARTE_LIVRO { get; set; }
        public Nullable<int> QTD_TOTAL { get; set; }
        public Nullable<int> QTD_APROVADA { get; set; }
        public Nullable<int> QTD_FINALIZADA { get; set; }
        public Nullable<int> QTD_CAIU { get; set; }
        public Nullable<int> QTD_REPROVADA { get; set; }
        public Nullable<int> QTD_AGUARDANDO_APROVACAO { get; set; }
        public Nullable<int> QTD_EM_PESQUISA { get; set; }
        public Nullable<int> QTD_APROVACAO_ORCAMENTO { get; set; }
        public System.DateTime DT_CADASTRO { get; set; }
        public Nullable<decimal> PORCENTAGEM_FINALIZADA { get; set; }
        public Nullable<int> QTD_OUTROS_STATUS { get; set; }
    }
}
