//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RESULTADO_PAGAMENTO_META
    {
        public System.Guid ID_RESULTADO_PAGAMENTO { get; set; }
        public int PORCENTAGEM_RESULTADO { get; set; }
        public int PORCENTAGEM_PAGAMENTO { get; set; }
        public System.DateTime DT_CADASTRO { get; set; }
    }
}
