//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_REGRA_ACESSO_ABA_CADASTRO_PRODUTO
    {
        public int ID_REGRA_ABA { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_ABA { get; set; }
        public bool ACESSO_MODIFICACAO { get; set; }
        public Nullable<bool> ACESSO_VISUALIZACAO { get; set; }
    
        public virtual TB_ABA_CADASTRO_PRODUTO TB_ABA_CADASTRO_PRODUTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
