//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_STATUS_PAINEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_STATUS_PAINEL()
        {
            this.TB_META_ANUAL = new HashSet<TB_META_ANUAL>();
            this.TB_META_FINANCEIRA = new HashSet<TB_META_FINANCEIRA>();
        }
    
        public System.Guid ID_STATUS { get; set; }
        public string DESCRICAO { get; set; }
        public System.DateTime DT_CADASTRO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_META_ANUAL> TB_META_ANUAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_META_FINANCEIRA> TB_META_FINANCEIRA { get; set; }
    }
}
