//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SISTEMA_ORIGEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_SISTEMA_ORIGEM()
        {
            this.TB_TABELA_ORIGEM = new HashSet<TB_TABELA_ORIGEM>();
        }
    
        public System.Guid ID_SISTEMA { get; set; }
        public string NOME_BANCO { get; set; }
        public System.DateTime DT_CADASTRO { get; set; }
        public bool ATIVO { get; set; }
        public string DESCRICAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TABELA_ORIGEM> TB_TABELA_ORIGEM { get; set; }
    }
}
