//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIO_RM_INTEGRACAO
    {
        public System.Guid ID_USUARIO { get; set; }
        public int CODIGO_FILIAL { get; set; }
        public string NOME_FILIAL { get; set; }
        public string CHAPA { get; set; }
        public string NOME { get; set; }
        public string CODFUNCAO { get; set; }
        public string FUNCAO { get; set; }
        public string CODSECAO { get; set; }
        public string DESCRICAO_SECAO { get; set; }
        public System.DateTime DT_INTEGRACAO { get; set; }
        public string CPF { get; set; }
        public Nullable<System.DateTime> DATA_INICIO { get; set; }
        public Nullable<System.DateTime> DATA_DEMISSAO { get; set; }
    }
}
