//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMPDATAPRODUCT
    {
        public int Id { get; set; }
        public int Id_Usuario { get; set; }
        public int Prod_id { get; set; }
        public int IdRegistro { get; set; }
        public string LabelRegistro { get; set; }
        public string Descricao { get; set; }
    }
}
