//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoBRA.IntegracaoProduto.WS.DAL.Acesso
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_GRUPO
    {
        public System.Guid ID_USUARIO_GRUPO { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_GRUPO { get; set; }
        public System.DateTime DT_CADASTRO { get; set; }
    }
}
